[package]
name = "gsoh"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
poise = "0.6.1"
reqwest = { version = "0.12.20", features = ["multipart", "stream"] }
tempfile = "3.20.0"
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }
zip = "4.1.0"
