[package]
name = "gsoh"
version = "0.1.0"
edition = "2024"

[dependencies]
curl = "0.4.48"
dotenvy = "0.15.7"
poise = "0.6.1"
serde = "1.0.219"
serde_json = "1.0.140"
tempfile = "3.20.0"
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }
zip = "4.1.0"
